#Google Analytics
analytics-id: #leave blank to not use Analytics

#Subtitle
subtitle:
  active: true
  text: Yet Another Minimal Theme

#Nav
nav:
  pages:
    active: false
  social:
    active: false

#Featured images in homepage
featured-img:
  active: false

#Show categories at the end of posts
categories:
  active: true

#Show date and read time under the post title
date-under-post:
  active: false

#Use MathJAX
mathjax:
  active: true

#Show related posts based on categories
related-posts:
  active: true
  title: "Cela pourrait vous intéresser :"

#Comments
comments: false
